// <auto-generated />
using System;
using App.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422225955_migrationInicial")]
    partial class migrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Entities.Agendamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientesId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("FoiPago")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("HorarioAgendamento")
                        .HasColumnType("interval");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("ServicosId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusAgendamento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientesId");

                    b.HasIndex("ServicosId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("App.Domain.Entities.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTelefone")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("App.Domain.Entities.FolgasFeriados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("ParametrosId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParametrosId", "Data")
                        .IsUnique();

                    b.ToTable("FolgasFeriados");
                });

            modelBuilder.Entity("App.Domain.Entities.Parametros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiasFuncionamento")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HorarioAbertura")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HorarioFechamento")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("App.Domain.Entities.Servicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("interval");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("App.Domain.Entities.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("NumeroTelefone")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("App.Domain.Entities.Agendamentos", b =>
                {
                    b.HasOne("App.Domain.Entities.Clientes", "Clientes")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.Servicos", "Servicos")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ServicosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("App.Domain.Entities.Clientes", b =>
                {
                    b.HasOne("App.Domain.Entities.Usuarios", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("App.Domain.Entities.Clientes", "UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("App.Domain.Entities.FolgasFeriados", b =>
                {
                    b.HasOne("App.Domain.Entities.Parametros", "Parametros")
                        .WithMany("FolgasFeriados")
                        .HasForeignKey("ParametrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parametros");
                });

            modelBuilder.Entity("App.Domain.Entities.Clientes", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("App.Domain.Entities.Parametros", b =>
                {
                    b.Navigation("FolgasFeriados");
                });

            modelBuilder.Entity("App.Domain.Entities.Servicos", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("App.Domain.Entities.Usuarios", b =>
                {
                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
